INSERT INTO categorie (name) VALUES 
('Parfums'),
('Eau de Parfum'),
('Eau de Toilette'),
('Brume pour le Corps'),
('Lotion Hydratante'),
('Huile pour le Corps');
-- ("Brume pour le corps"), 
-- ("Parfum pour femme"),
-- ("Parfum pour homme"),
-- ("Parfum unisexe"),
-- ("Eau de toilette"),
-- ("Eau de parfum"),
-- ("Parfum de niche"),
-- ("Parfum artisanal"),
-- ("Parfum oriental"),
-- ("Parfum fruité"),
-- ("Parfum floral"),
-- ("Parfum boisé"),
-- ("Parfum gourmand"),
-- ("Parfum oriental épicé"),
-- ("Parfum d'été"),
-- ("Parfum de luxe"),
-- ("Eau fraîche"),
-- ("Parfum au patchouli"),
-- ("Parfum à la vanille"),
-- ("Parfum aux agrumes"),
-- ("Parfum boisé et épicé"),
-- ("Parfum cuir et tabac"),
-- ("Parfum boisé et cuir"),
-- ("Parfum gourmand sucré"),
-- ("Parfum aquatique"),
-- ("Parfum floral poudré"),
-- ("Parfum épicé"),
-- ("Parfum à la fleur d'oranger"),
-- ("Parfum à la cannelle"),
-- ("Parfum au bois de cèdre"),
-- ("Parfum floral oriental"),
-- ("Parfum doux et fruité"),
-- ("Parfum sensuel"),
-- ("Parfum à la figue"),
-- ("Parfum à la bergamote"),
-- ("Parfum à l'oud"),
-- ("Parfum floral aquatique"),
-- ("Parfum sucré épicé"),
-- ("Parfum musqué léger"),
-- ("Parfum au gingembre"),
-- ("Parfum à la fleur de cerisier"),
-- ("Parfum aux fruits rouges"),
-- ("Parfum au bois de santal"),
-- Lotions
-- ("Lotion hydratante"),

-- Huiles
-- ("Huile pour le corps"),

-- Muscs
-- ("Musc traditionnel"),
-- ("Musc en roll-on"),
-- ("Musc solide"),
-- ("Musc en spray"),
-- ("Musc oriental"),
-- ("Musc doux"),
-- ("Musc intense"),
-- ("Musc floral"),
-- ("Musc boisé"),
-- ("Musc vanillé"),
-- ("Musc au santal"),
-- ("Musc floral et fruité"),
-- ("Musc oriental doux"),
-- ("Musc ambré"),
-- ("Musc aux épices"),
-- ("Musc exotique"),
-- ("Musc oriental intense"),
-- ("Musc à la vanille et ambre"),
-- ("Musc frais et léger"),
-- ("Musc à la rose"),
-- ("Musc au bois de oud"),
-- ("Musc fleuri"),
-- ("Musc fruité doux"),
-- ("Musc épicé à la cardamome"),
-- ("Musc aux agrumes"),
-- ("Musc au patchouli"),
-- ("Musc à l'ambre gris");