-- Parfums
INSERT INTO product (name, description, price, stock, categorie_id) 
VALUES 
("Eau de Toilette Femme - Jasmine Elegance", "Un parfum féminin léger aux notes de jasmin.", 45.00, 100, 1),
("Parfum Homme - Leather & Cedar", "Un parfum masculin riche avec des notes de cuir et de cèdre.", 55.00, 80, 2),
("Parfum Unisexe - Citrus Breeze", "Un parfum frais et fruité, adapté aux deux sexes.", 50.00, 150, 3),
("Eau de Parfum - Midnight Oud", "Un parfum intense et envoûtant à base d'oud.", 75.00, 60, 4),
("Parfum de Niche - Velvet Orchid", "Un parfum exclusif avec des notes de vanille et d'orchidée.", 90.00, 40, 5),
("Parfum Artisanal - Cedarwood Harmony", "Un parfum artisanal avec une harmonie de bois de cèdre.", 65.00, 50, 6),
("Parfum Oriental - Desert Sands", "Un parfum oriental chaleureux avec des notes épicées.", 70.00, 70, 7),
("Parfum Fruité - Tropical Mango", "Un parfum fruité rafraîchissant avec des notes de mangue.", 48.00, 120, 8),
("Parfum Floral - Rose Petals", "Un parfum floral délicat avec des pétales de rose.", 55.00, 90, 9),
("Parfum Boisé - Forest Whisper", "Un parfum boisé avec des nuances de forêt.", 60.00, 85, 10),
("Parfum Gourmand - Sweet Caramel", "Un parfum gourmand avec des notes sucrées de caramel.", 50.00, 110, 11),
("Parfum Oriental Épicé - Spiced Incense", "Un parfum oriental avec des épices et de l'encens.", 68.00, 65, 12),
("Parfum d'Été - Cool Coconut", "Un parfum d'été léger aux notes de noix de coco.", 42.00, 130, 13),
("Parfum de Luxe - Golden Amber", "Un parfum de luxe avec des notes d'ambre doré.", 95.00, 30, 14),
("Eau Fraîche - Spring Citrus", "Une eau fraîche avec des notes d'agrumes printaniers.", 38.00, 140, 15),
("Parfum au Patchouli - Earthy Patchouli", "Un parfum terreux et riche en patchouli.", 52.00, 100, 16),
("Parfum à la Vanille - Vanilla Dream", "Un parfum doux avec des notes de vanille.", 45.00, 110, 17),
("Parfum aux Agrumes - Zesty Lemon", "Un parfum frais et acidulé avec des agrumes.", 48.00, 120, 18),
("Parfum Boisé et Épicé - Woody Spice", "Un parfum avec des notes boisées et épicées.", 60.00, 80, 19),
("Parfum Cuir et Tabac - Smoky Leather", "Un parfum riche en cuir et tabac.", 65.00, 70, 20),
("Parfum Boisé et Cuir - Forest Leather", "Un parfum combinant bois et cuir.", 62.00, 75, 21),
("Parfum Gourmand Sucré - Sweet Almond", "Un parfum gourmand avec des notes d'amande sucrée.", 50.00, 100, 22),
("Parfum Aquatique - Ocean Mist", "Un parfum aquatique léger avec des notes maritimes.", 44.00, 125, 23),
("Parfum Floral Poudré - Powdered Lily", "Un parfum floral avec une touche poudrée de lys.", 53.00, 85, 24),
("Parfum Épicé - Warm Cinnamon", "Un parfum épicé avec des notes de cannelle.", 47.00, 95, 25),
("Parfum à la Fleur d'Oranger - Orange Blossom Delight", "Un parfum floral avec des notes de fleur d'oranger.", 57.00, 80, 26),
("Parfum à la Cannelle - Spiced Cinnamon", "Un parfum épicé avec une dominante de cannelle.", 50.00, 90, 27),
("Parfum au Bois de Cèdre - Cedar Essence", "Un parfum boisé avec des notes de cèdre.", 55.00, 85, 28),
("Parfum Floral Oriental - Exotic Bloom", "Un parfum floral avec des nuances orientales.", 60.00, 70, 29),
("Parfum Doux et Fruité - Berry Bliss", "Un parfum doux avec des notes de baies.", 52.00, 100, 30),
("Parfum Sensuel - Sensual Musk", "Un parfum sensuel avec des notes de musc.", 65.00, 60, 31),
("Parfum à la Figue - Fig Infusion", "Un parfum fruité avec des notes de figue.", 58.00, 75, 32),
("Parfum à la Bergamote - Bergamot Essence", "Un parfum frais avec des notes de bergamote.", 46.00, 90, 33),
("Parfum à l'Oud - Royal Oud", "Un parfum royal et riche à base d'oud.", 80.00, 45, 34),
("Parfum Floral Aquatique - Aqua Blossom", "Un parfum floral avec des notes aquatiques.", 50.00, 85, 35),
-- -- Parfums (suite)
("Parfum Sucré Épicé - Sweet Spice", "Un parfum sucré avec des nuances épicées.", 55.00, 80, 36),
("Parfum Musqué Léger - Light Musk", "Un parfum musqué léger et subtil.", 48.00, 100, 37),
("Parfum au Gingembre - Ginger Spice", "Un parfum épicé avec des notes de gingembre.", 52.00, 85, 38),
("Parfum à la Fleur de Cerisier - Cherry Blossom", "Un parfum floral avec des notes de fleur de cerisier.", 57.00, 70, 39),
("Parfum aux Fruits Rouges - Red Fruit Delight", "Un parfum fruité avec des baies rouges.", 53.00, 90, 40),
("Parfum au Bois de Santal - Sandalwood Serenity", "Un parfum boisé avec des notes de bois de santal.", 60.00, 80, 41),

-- -- Lotions
("Lotion Hydratante - Aloe & Cucumber", "Lotion hydratante avec de l'aloe et du concombre.", 25.00, 150, 42),
("Lotion Après-Rasage - Soothing Balm", "Lotion apaisante après le rasage.", 22.00, 100, 43),
("Lotion Anti-Pollution - Urban Shield", "Lotion anti-pollution pour une peau protégée.", 30.00, 80, 44),
("Lotion Détoxifiante - Detox Cleanse", "Lotion détoxifiante pour une peau purifiée.", 28.00, 90, 45),
("Lotion Éclat du Teint - Radiance Boost", "Lotion illuminatrice pour un teint éclatant.", 27.00, 110, 46),
("Lotion Apaisante pour Peaux Sensibles - Gentle Comfort", "Lotion douce pour peaux sensibles.", 24.00, 120, 47),
("Lotion Clarifiante à l'Acide Glycolique - Clear Glow", "Lotion clarifiante avec acide glycolique.", 32.00, 85, 48),
("Lotion Nourrissante au Beurre de Karité - Shea Butter Bliss", "Lotion nourrissante au beurre de karité.", 29.00, 95, 49),
("Lotion Anti-Rides - Age Defy", "Lotion anti-rides pour une peau jeune.", 34.00, 70, 50),

-- -- Brumes
("Brume pour le Corps - Refreshing Mint", "Brume pour le corps avec une touche de menthe.", 20.00, 150, 51),
("Brume Énergisante - Citrus Burst", "Brume vivifiante aux agrumes.", 22.00, 140, 52),
("Brume Aromathérapie - Calming Lavender", "Brume aromathérapeutique à la lavande.", 21.00, 130, 53),
("Brume au Jasmin - Jasmine Essence", "Brume légère avec des notes de jasmin.", 23.00, 120, 54),
("Brume à la Lavande - Lavender Calm", "Brume apaisante avec de la lavande.", 21.00, 125, 55),
("Brume Rafraîchissante au Concombre - Cucumber Cool", "Brume rafraîchissante au concombre.", 19.00, 140, 56),
("Brume au Citron - Lemon Zest", "Brume vivifiante aux notes de citron.", 22.00, 135, 57),
("Brume Revitalisante au Pamplemousse - Grapefruit Kick", "Brume revitalisante avec des notes de pamplemousse.", 24.00, 125, 58),
("Brume Apaisante au Miel - Honey Relax", "Brume apaisante avec des notes de miel.", 23.00, 130, 59),
("Brume Fraîcheur à l'Eucalyptus - Eucalyptus Breeze", "Brume fraîche avec de l'eucalyptus.", 21.00, 145, 60),

-- -- Huiles
("Huile pour le Corps - Nourishing Argan", "Huile corporelle nourrissante à l'argan.", 35.00, 80, 61),
("Huile Régénérante au Rétinol - Retinol Renew", "Huile régénérante avec du rétinol.", 40.00, 70, 62),
("Huile Revitalisante à la Vitamine E - Vitamin E Glow", "Huile revitalisante avec de la vitamine E.", 38.00, 85, 63),
("Huile Corporelle à la Lavande - Lavender Body Oil", "Huile corporelle relaxante à la lavande.", 34.00, 90, 64),
("Huile de Monoï - Tropical Monoï", "Huile de monoï tropicale pour la peau.", 37.00, 75, 65),
("Huile Capillaire à la Kératine - Keratin Hair Oil", "Huile capillaire nourrissante à la kératine.", 36.00, 80, 66),
("Huile pour le Cuir Chevelu Sec - Scalp Hydrate", "Huile pour cuir chevelu sec et hydraté.", 33.00, 85, 67),
("Huile Anti-Frisottis - Frizz Control", "Huile anti-frisottis pour cheveux lisses.", 32.00, 80, 68),
("Huile de Soin pour les Lèvres - Lip Care Oil", "Huile nourrissante pour les lèvres.", 18.00, 100, 69),
("Huile de Tamanu - Tamanu Repair", "Huile de tamanu réparatrice pour la peau.", 37.00, 75, 70),

-- -- Muscs
("Musc Traditionnel - Classic Musk", "Musc traditionnel avec une fragrance classique.", 28.00, 100, 71),
("Musc en Roll-On - Convenient Musk", "Musc en roll-on pratique pour une application facile.", 25.00, 110, 72),
("Musc Solide - Solid Musk Bar", "Musc solide pour une utilisation longue durée.", 30.00, 90, 48),
("Musc en Spray - Spray Musk", "Musc en spray pour une application rapide.", 27.00, 95, 49),
("Musc Oriental - Oriental Mystique", "Musc oriental avec des notes mystérieuses.", 32.00, 85, 50),
("Musc Doux - Soft Musk", "Musc doux et léger pour une touche subtile.", 26.00, 100, 51),
("Musc Intense - Intense Musk", "Musc intense avec une fragrance puissante.", 35.00, 80, 52),
("Musc Floral - Floral Essence", "Musc avec des nuances florales.", 29.00, 90, 53),
("Musc Boisé - Woody Musk", "Musc avec des notes boisées.", 31.00, 85, 54),
("Musc Vanillé - Vanilla Musk", "Musc doux avec des notes de vanille.", 28.00, 95, 55),
("Musc au Santal - Sandalwood Musk", "Musc riche avec des notes de bois de santal.", 34.00, 75, 56),
("Musc Floral et Fruité - Floral Fruity Musk", "Musc combinant des notes florales et fruitées.", 30.00, 80, 57),
("Musc Oriental Doux - Soft Oriental Musk", "Musc oriental avec une touche douce.", 33.00, 70, 50),
("Musc Ambré - Amber Musk", "Musc avec des notes ambrées.", 36.00, 65, 59),
("Musc aux Épices - Spiced Musk", "Musc avec des notes épicées.", 32.00, 75, 60),
("Musc Exotique - Exotic Musk", "Musc avec des notes exotiques.", 35.00, 60, 61),
("Musc Oriental Intense - Intense Oriental Musk", "Musc oriental avec une fragrance intense.", 38.00, 55, 50),
("Musc à la Vanille et Ambre - Vanilla Amber Musk", "Musc combinant vanille et ambre.", 37.00, 65, 55),
("Musc Frais et Léger - Fresh Light Musk", "Musc léger avec une touche fraîche.", 29.00, 80, 64),
("Musc à la Rose - Rose Musk", "Musc avec des notes de rose.", 28.00, 85, 65),
("Musc au Bois de Oud - Oud Wood Musk", "Musc avec des notes de bois de oud.", 40.00, 50, 66),
("Musc Fleuri - Floral Musk", "Musc avec des nuances fleuries.", 27.00, 90, 67),
("Musc Fruité Doux - Sweet Fruity Musk", "Musc doux avec des notes fruitées.", 28.00, 85, 68),

-- -- Muscs (suite)
("Musc Épicé à la Cardamome - Cardamom Spice Musk", "Musc avec des notes épicées de cardamome.", 31.00, 80, 69),
("Musc aux Agrumes - Citrus Musk", "Musc frais avec des notes d'agrumes.", 29.00, 85, 70),
("Musc au Patchouli - Patchouli Musk", "Musc riche avec des notes de patchouli.", 34.00, 70, 71),
("Musc à l'Ambre Gris - Grey Amber Musk", "Musc avec des notes d'ambre gris.", 37.00, 65, 72);